class Locators:
    continue_btn = '//button[@class="css-1fzhd9j"]'
    search_icon = '//button[@data-element="search-button"]'
    search_input = '//input[@data-element="search-form-input"]'
    search_submit = '//button[@data-element="search-submit-button"]'
    see_all_btn = '//p[text()="Topics"]//ancestor::ps-toggler//button[@class="button see-all-button"]'
    topics = '//ul[@data-name="Topics"]//input[@class="checkbox-input-element"]'
    sort_btn = '//select'
    newest_option = '//select[@class="select-input"]//option[text()="Newest"]'
    date_specific = '//button[@value="Specific Dates"]'
    input_start_date = '//input[@id="startDate"]'
    input_end_date = '//input[@id="endDate"]'
    section_btn = '//label[text()="Section"]'
    section_check = '//input[@value="Blogs|nyt://section/7dc9a77b-5567-500d-a633-12f9d14786aa"]'
    search_result = '//div[@class="promo-content"]'
    title = '//h3[@class="promo-title"]'
    description = '//p[@class="promo-description"]'
    date = '//p[@class="promo-timestamp"]'
    image = '//img[@class="image"]'